Registry.require("promise helper i18n xmlhttprequest uri permission convert".split(" "),function(){var d={DEFAULT:"default",OFF:"off",NATIVE:"native",CHROME:"chrome",NOT_ENABLED:"not_enabled",NOT_WHITELISTED:"not_whitelisted",NOT_PERMITTED:"not_permitted",NOT_SUPPORTED:"not_supported",NOT_SUCCEEDED:"not_succeeded"},e=Registry.log,t=rea.FEATURES,k=Registry.get("promise"),n=Registry.get("helper"),h=Registry.get("permission"),u=Registry.get("i18n"),A=Registry.get("xmlhttprequest"),B=Registry.get("uri"),
C=Registry.get("convert"),D=A.run,l=d.OFF,v=[],m=null,w=!1,p={},x=!1,y=function(){var a=k();Registry.vendor(["vendor/saveas/filesaver"],function(){y=k.Pledge;a.resolve()});return a.promise()},q=function(){return null!==m?k.Pledge(m):!rea.permissions.supported&&rea.downloads.supported?(m=!0,k.Pledge(m)):h.has(h.permDownloads).then(function(a){m=a;e.debug("downs: permission to use rea.downloads ->",a);return q()})},E=function(a,b){if(this[a])this[a]("function"==typeof b?b():b)},r=function(a,b){this[a]&&
(E.apply(this,arguments),this[a]=null)},G=function(a,b){m&&!x&&rea.downloads.supported&&(rea.downloads.onChanged.addListener(F),x=!0);var c={filename:a.name},g;t.RUNTIME.FIREFOX&&52>t.RUNTIME.BROWSER_VERSION?g=["url"]:(g=["url","method","saveAs","headers"],c.body=a.data);g.forEach(function(b){c[b]=a[b]});rea.downloads.download(c,function(c){p[c]={callbacks:b,url:a.url,name:a.name}})},H=function(a,b){void 0===b&&(b={});var c=function(){return r.apply(b,arguments)};a.responseType="blob";a.method=a.method||
"GET";D(a,{onload:function(b){if(4!=b.readyState||200!=b.status&&0!=b.status||b.error)c("onerror",{});else{var f=null;(b.responseHeaders?b.responseHeaders.split("\n"):[]).forEach(function(a){var b=a.split(":");a=b.shift()||"";b=b.join(":")||"";"content-type"==a.trim().toLowerCase()&&(f=b.trim())});b=new Blob([b.response],{type:a.overrideMimeType||f||"binary/octet-stream"});saveAs(b,a.name);c("onload",{})}},ondone:function(){c("ondone",{})},onerror:b.onerror,ontimeout:b.ontimeout,onprogress:b.onprogress})},
F=function(a){var b=p[a.id];if(b){var c=b.callbacks,g=function(){return r.apply(c,arguments)};if(a.error)e.warn("downs: download of",b.name,"("+b.url+")","failed",a.error),g("onerror",{error:d.NOT_SUCCEEDED,details:a.error});else if(a.endTime||a.state&&"complete"==a.state.current)e.debug("downs: download of",b.name,"("+b.url+")","finished"),g("onload",{}),g("ondone",{}),delete p[a.id]}},z=function(a){var b=!1;n.each(v,function(c,g){if(c&&c.length)try{var f;if("/"===c[0])c=c.replace(/^\//g,"").replace(/\/$/g,
""),"$"!==c[c.length-1]&&(e.debug("downs: patching $ into",c),c+="$"),f=new RegExp(c,"i");else if("."===c[0]){var d=[n.escapeForRegExp(c),"$"].join("");f=new RegExp(d,"i")}else e.warn("downs: invalid file extension:",'"'+c+'"','starts neither with "." nor with "/"');if(f&&-1!==a.search(f))return e.debug("downs:",c,"matched @",a),b=!0}catch(h){e.warn("downs: can't process",c,h)}});return b};Registry.register("downloads","5665",{start:function(a,b){var c=this,g=arguments,f=function(){return r.apply(b,
arguments)};e.debug("downs: start",a);if(!a.internal){if(l==d.OFF){e.warn("downs: feature is not enabled");f("onerror",{error:d.NOT_ENABLED});return}if(!a.name||!z(a.name)){e.warn("downs:",a.name,"is not whitelisted");f("onerror",{error:d.NOT_WHITELISTED});return}if(!rea.downloads.supported&&l==d.CHROME){e.warn("downs: this download mode is not supported");f("onerror",{error:d.NOT_SUPPORTED});return}}(function(){return!rea.downloads.supported||l!=d.CHROME&&l!=d.DEFAULT?k.Breach():q().then(function(a){if(a)G.apply(c,
g);else if(l==d.CHROME)e.warn("downs: download permission is missing"),f("onerror",{error:d.NOT_PERMITTED});else return k.Breach()})})().fail(function(){var b=B.parse(a.url);a.name=a.name||"File.download";y().done(function(){"data:"==b.protocol?saveAs(C.dataURItoBlob(a.url),a.name):H.apply(c,g)})})},set_mode:function(a){l=a;l==d.CHROME&&q().done(function(a){a||h.has(h.permDownloads).then(function(a){var b=k();w||a?b.resolve({permission:a,asked:!1}):h.ask(h.permDownloads,u.getMessage("Browser_API_Downloads"),
u.getMessage("Click_here_to_allow_TM_to_start_downloads")).done(function(a){b.resolve({permission:a,asked:!0})});w=!0;return b.promise()}).done(function(a){a.permission&&a.asked&&rea.page.reload()})})},set_whitelist:function(a){"Array"===n.toType(a)&&(v=a)},is_whitelisted:z,remove_permission:function(){return h.remove(h.permDownloads)},staticVars:d})});
