# Shell variables
# Generated by 'wal'
wallpaper='/home/ysen/.config/wpg/wallpapers/no_love.png'

# Special
background='#0e0e0e'
foreground='#fffcfa'
cursor='#ebe5e3'

# Colors
color0='#0e0e0e'
color1='#2B4DAE'
color2='#908F90'
color3='#A39D9D'
color4='#B0AFB0'
color5='#CFB2B3'
color6='#D0CFD0'
color7='#ebe5e3'
color8='#222222'
color9='#295df0'
color10='#cda7cd'
color11='#e8b7b7'
color12='#fbccfb'
color13='#ffced1'
color14='#ffe4ff'
color15='#fffcfa'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
