[Icon Theme]
Name=Mist
Name[af]=Mis
Name[ar]=غشى
Name[as]=কুঁৱলী
Name[ast]=Ñeblina
Name[az]=Çən
Name[be]=Туман
Name[be@latin]=Mist
Name[bg]=Мъгла
Name[bn]=কুয়াশা
Name[bn_IN]=কুয়াশা
Name[br]=Arlun ha testenn mut
Name[bs]=Magla
Name[ca]=Boira
Name[ca@valencia]=Boira
Name[crh]=Sis
Name[cs]=Mlha
Name[cy]=Niwl
Name[da]=Tåge
Name[de]=Dunst
Name[dz]=སྨུག་ཟིལ།
Name[el]=Μινιμαλίστικο
Name[en@shaw]=·𐑥𐑦𐑕𐑑
Name[en_CA]=Mist
Name[en_GB]=Mist
Name[es]=Bruma
Name[et]=Udu
Name[eu]=Lainobera
Name[fa]=مه
Name[fi]=Sumu
Name[fr]=Mist
Name[fur]=Fumate
Name[ga]=Mist
Name[gl]=Brétema
Name[gu]=ધૂંધળુ
Name[he]=ערפל
Name[hi]=धुंध
Name[hr]=Mist
Name[hu]=Ködös
Name[id]=Kabut
Name[is]=Þoka
Name[it]=Nebbia
Name[ja]=ミスト
Name[ka]=ნისლი
Name[kn]=ಇಬ್ಬನಿ
Name[ko]=흐림
Name[ky]=Мунарык
Name[li]=Moet
Name[lt]=Migla
Name[lv]=Mist
Name[mai]=धुन्ध
Name[mg]=Mist
Name[mk]=Mist
Name[ml]=മൂടല്‍ മഞ്ഞ്
Name[mn]=Униарт
Name[mr]=धुकं
Name[ms]=Mist
Name[nb]=Tåke
Name[nds]=Kroom
Name[ne]=कुइरो
Name[nl]=Mist
Name[nn]=Dis
Name[oc]=Nèbla
Name[or]=କୁହୁଡ଼ି
Name[pa]=ਧੁੰਦਲਾ
Name[pl]=Zamglony
Name[pt]=Místico
Name[pt_BR]=Neblina
Name[ro]=Mist
Name[ru]=Мгла
Name[si]=මීදුම
Name[sk]=Opar
Name[sl]=Meglice
Name[sq]=Mjegull
Name[sr]=Магла
Name[sr@latin]=Magla
Name[sv]=Dimma
Name[ta]=மூடுபனி
Name[te]=పొగమంచు
Name[th]=หมอก
Name[tr]=Sis
Name[ug]=سۈزۈك تۇمان
Name[uk]=Серпанок
Name[vi]=Sương mù
Name[wa]=Brouheur
Name[xh]=Inkungu
Name[zh_CN]=薄雾
Name[zh_HK]=薄霧
Name[zh_TW]=薄霧
Comment=Mist
Comment[af]=Mis
Comment[ar]=غشى
Comment[as]=কুঁৱলী
Comment[ast]=Ñeblina
Comment[az]=Çən
Comment[be]=Туман
Comment[be@latin]=Mist
Comment[bg]=Мъгла
Comment[bn]=কুয়াশা
Comment[bn_IN]=কুয়াশা
Comment[br]=Arlun ha testenn mut
Comment[bs]=Magla
Comment[ca]=Boira
Comment[ca@valencia]=Boira
Comment[crh]=Sis
Comment[cs]=Mlha
Comment[cy]=Niwl
Comment[da]=Tåge
Comment[de]=Dunst
Comment[dz]=སྨུག་ཟིལ།
Comment[el]=Μινιμαλίστικο
Comment[en@shaw]=·𐑥𐑦𐑕𐑑
Comment[en_CA]=Mist
Comment[en_GB]=Mist
Comment[es]=Bruma
Comment[et]=Udu
Comment[eu]=Lainobera
Comment[fa]=مه
Comment[fi]=Sumu
Comment[fr]=Mist
Comment[fur]=Fumate
Comment[ga]=Mist
Comment[gl]=Brétema
Comment[gu]=ધૂંધળુ
Comment[he]=ערפל
Comment[hi]=धुंध
Comment[hr]=Mist
Comment[hu]=Ködös
Comment[id]=Kabut
Comment[is]=Þoka
Comment[it]=Nebbia
Comment[ja]=ミスト
Comment[ka]=ნისლი
Comment[kn]=ಇಬ್ಬನಿ
Comment[ko]=흐림
Comment[ky]=Мунарык
Comment[li]=Moet
Comment[lt]=Migla
Comment[lv]=Mist
Comment[mai]=धुन्ध
Comment[mg]=Mist
Comment[mk]=Mist
Comment[ml]=മൂടല്‍ മഞ്ഞ്
Comment[mn]=Униарт
Comment[mr]=धुकं
Comment[ms]=Mist
Comment[nb]=Tåke
Comment[nds]=Kroom
Comment[ne]=कुइरो
Comment[nl]=Mist
Comment[nn]=Dis
Comment[oc]=Nèbla
Comment[or]=କୁହୁଡ଼ି
Comment[pa]=ਧੁੰਦਲਾ
Comment[pl]=Zamglony
Comment[pt]=Místico
Comment[pt_BR]=Neblina
Comment[ro]=Mist
Comment[ru]=Мгла
Comment[si]=මීදුම
Comment[sk]=Opar
Comment[sl]=Meglice
Comment[sq]=Mjegull
Comment[sr]=Магла
Comment[sr@latin]=Magla
Comment[sv]=Dimma
Comment[ta]=மூடுபனி
Comment[te]=పొగమంచు
Comment[th]=หมอก
Comment[tr]=Sis
Comment[ug]=سۈزۈك تۇمان
Comment[uk]=Серпанок
Comment[vi]=Sương mù
Comment[wa]=Brouheur
Comment[xh]=Inkungu
Comment[zh_CN]=薄雾
Comment[zh_HK]=薄霧
Comment[zh_TW]=薄霧
Inherits=gnome
Directories=22x22/status,22x22/devices,22x22/actions,22x22/places,22x22/apps,16x16/status,16x16/devices,16x16/actions,16x16/places,16x16/apps,32x32/status,32x32/devices,32x32/actions,32x32/places,32x32/apps,48x48/status,48x48/devices,48x48/actions,48x48/places,48x48/apps,24x24/status,24x24/devices,24x24/actions,24x24/places,24x24/apps,256x256/status,256x256/devices,256x256/actions,256x256/places,256x256/apps

[22x22/status]
Size=22
Context=Status
Type=Fixed

[22x22/devices]
Size=22
Context=Devices
Type=Fixed

[22x22/actions]
Size=22
Context=Actions
Type=Fixed

[22x22/places]
Size=22
Context=Places
Type=Fixed

[22x22/apps]
Size=22
Context=Apps
Type=Fixed

[16x16/status]
Size=16
Context=Status
Type=Fixed

[16x16/devices]
Size=16
Context=Devices
Type=Fixed

[16x16/actions]
Size=16
Context=Actions
Type=Fixed

[16x16/places]
Size=16
Context=Places
Type=Fixed

[16x16/apps]
Size=16
Context=Apps
Type=Fixed

[32x32/status]
Size=32
Context=Status
Type=Fixed

[32x32/devices]
Size=32
Context=Devices
Type=Fixed

[32x32/actions]
Size=32
Context=Actions
Type=Fixed

[32x32/places]
Size=32
Context=Places
Type=Fixed

[32x32/apps]
Size=32
Context=Apps
Type=Fixed

[48x48/status]
Size=48
Context=Status
Type=Fixed

[48x48/devices]
Size=48
Context=Devices
Type=Fixed

[48x48/actions]
Size=48
Context=Actions
Type=Fixed

[48x48/places]
Size=48
Context=Places
Type=Fixed

[48x48/apps]
Size=48
Context=Apps
Type=Fixed

[24x24/status]
Size=24
Context=Status
Type=Fixed

[24x24/devices]
Size=24
Context=Devices
Type=Fixed

[24x24/actions]
Size=24
Context=Actions
Type=Fixed

[24x24/places]
Size=24
Context=Places
Type=Fixed

[24x24/apps]
Size=24
Context=Apps
Type=Fixed

[256x256/status]
Size=256
Context=Status
Type=Fixed

[256x256/devices]
Size=256
Context=Devices
Type=Fixed

[256x256/actions]
Size=256
Context=Actions
Type=Fixed

[256x256/places]
Size=256
Context=Places
Type=Fixed

[256x256/apps]
Size=256
Context=Apps
Type=Fixed

