Registry.require(["crcrc","helper","layout/default/htmlutil","i18n","layout/default/layout_helper"],function(){var w=rea.FEATURES,t=Registry.get("crcrc").cr,h=Registry.get("crcrc").crc,y=Registry.get("helper"),u=Registry.get("layout/default/htmlutil"),k=Registry.get("i18n"),z=Registry.get("layout"),A=Registry.get("layout/default/layout_helper"),v=A.images,m=3;if(w.RUNTIME.MOBILE)try{window.matchMedia("(orientation: portrait)").matches&&(m=1)}catch(n){}z.render(function(){var n={};A.addStyle();var K=
function(b,a){var d=[];if(a.sub_menu_item){if(a.items.length){var c=h("table","actiontable","actiontable-"+a.name);B(c,a.items);d.push(c)}}else if(c=null,a.image?c=u.createIcon(v.get(a.image),a.name,a.id,null,""):a.enabler&&(c=u.createIcon(v.get(n.enabled?"button_ok":"cancel"),a.name,a.uuid,null,"")),c&&d.push(c),a.url||a.urls){for(var c=t("span",a.name,a.id,"urls"),g=a.urls||[a],e=0;e<g.length;e++){var f=g[e],p=document.createElement("span");p.textContent=f.name;var q=a.urls?p:b;q.url=f.url;q.newtab=
f.newtab;$(q).addClass("clickable").on("click auxclick",function(a){C(this.url,this.newtab);a.preventDefault()});c.appendChild(p);e<g.length-1&&(f=document.createElement("span"),f.textContent=" | ",c.appendChild(f))}d.push(c)}else if(a.menucmd){var l=document.createElement("span");b.id=a.id;g=function(){F(this.id,function(){w.ACTIONMENU.CLOSE_ALLOWED&&window.close()})};b.addEventListener("click",g);$(b).addClass("clickable");l.textContent=a.name;a.accessKey&&(c=a.accessKey[0].toUpperCase(),G(c,g,
b)?(g=new RegExp(c,"i"),e=l.textContent.search(g),f=[],-1==e&&(l.textContent+=" ("+c+")",e=l.textContent.search(g)),f.push({text:l.textContent.substr(0,e)}),f.push({text:l.textContent.substr(e,1),class:"underlined"}),f.push({text:l.textContent.substr(e+1)}),l.textContent="",f.forEach(function(c){var b=h("span",c.class||"",a.id,c);b.textContent=c.text;l.appendChild(b)})):console.warn("Registering keyboard shortcut for '"+a.name+"' failed"));d.push(l)}else if(a.button)c=h("span",a.display||"",a.name,
a.id,"bu",!0),c.textContent=a.name,b.key=a.id,b.warning=a.warning,b.reload=a.reload,b.data=a.data,b.addEventListener("click",function(){var a=!0;this.warning&&(a=H(this.warning));a&&I(this.key,{reload:this.reload,data:this.data})}),$(b).addClass("clickable"),d.push(c);else if(a.userscript){var c=h("div","clickable",a.name,a.uuid,"ai"),r;if(a.uuid&&(e=null,e=a.blacklisted?"enabler_warning":a.enabled?a.contexter?"enabler_enabled enabler_later":"enabler_enabled":"enabler_disabled",f=a.blacklisted?k.getMessage("This_script_is_blacklisted_"):
a.enabled?k.getMessage("Enabled"):k.getMessage("Disabled"),g=function(a){if(a&&(0!=a.button||a.ctrlKey||a.metaKey))return C(rea.extension.getURL("options.html")+"#nav="+this.key,!0),a.stopPropagation(),a.preventDefault(),!1;J(this.uuid,"enabled",!this.oldvalue)},f=u.createEnabler(e,a.uuid,"enabled",{append:"enabled",disabled:a.blacklisted,title:f},g),f.oldvalue=a.enabled,d.push(f),e=h("div",e,a.name,a.uuid,"name"),e.textContent=k.getTranslation(a,"name"),c.appendChild(e),c.uuid=a.uuid,c.oldvalue=
a.enabled,c.key=a.uuid,$(c).on("click auxclick",g),a.blacklisted&&(b.setAttribute("title",k.getMessage("This_script_is_blacklisted_")),$(c).addClass("crossedout")),g=[],a.nnew||a.system||!a.abuse||(e=h("div","action_issue",a.name,a.uuid,"action_issue"),p=u.createIcon(v.get("flag"),"",a.uuid,"issue",k.getMessage("Report_an_issue_to_the_script_hoster_")),f=h("span","",a.name,a.uuid,"action_issue_expl"),f.textContent=k.getMessage("Report_an_issue_to_the_script_hoster_").split(/[\.\(]+/)[0],e.appendChild([p,
f]),$(e).click(function(){D(a.uuid,"hoster")}),g.push(e)),a.nnew||a.system||!a.support||(e=h("div","action_issue",a.name,a.uuid,"action_bug"),p=u.createIcon(v.get("bug"),"",a.uuid,"bug",k.getMessage("Report_a_bug")),f=h("span","",a.name,a.uuid,"action_issue_expl"),f.textContent=k.getMessage("Report_a_bug"),e.appendChild([p,f]),$(e).click(function(){D(a.uuid,"author")}),g.push(e)),g.length)){r=h("div","actionenablercol",a.name,a.uuid,"actionenablercol");e=h("i","actionenabler clickable far fa-"+v.get("enabler"),
a.name,a.uuid,"actionenabler");$("body").click(function(){$(".action_issues").hide()});$(e).click(function(a){var c=$(r).find(".action_issues");$(c).is(":visible")||$(".action_issues").hide();c.toggle();a.stopPropagation()});var m=h("div","action_issues",a.name,a.uuid,"action_bug");g.forEach(function(a){m.appendChild(a)});m.setAttribute("style","display:none;");r.appendChild(m);r.appendChild(e)}d.push(c);r&&d.push(r)}else c=t("span",a.name,a.id,"ai"),c.textContent=a.name,d.push(c);return d},B=function(b,
a,d){Object.keys(a).forEach(function(c){var g=a[c];if(!b)if(d[g.pos])g.items&&g.items.length&&$(d[g.pos]).show();else{console.warn("Warn(cAm): unknown pos "+g.pos);return}var e=(c=b||d[g.pos])?t("tr",g.name,g.uuid||g.id,"outer"):null,f=K(e,g);if(f&&f.length){c.appendChild(e);var h;for(c=0;h=f[c];c++){var k=c==f.length-1?3-c:0,l=t("td","actiontd",g.name,g.uuid||g.id,c);0<k&&l.setAttribute("colspan",k);h&&l.appendChild(h);e.appendChild(l)}}})},E=function(b){var a=$("#action"),d=t("div");d.setAttribute("id",
"action");a.replaceWith(d);var c=h("table","actionlayout","actionlayout");d.appendChild(c);d=h("tr","actionpostr","hor");a=h("td","actionpostd","hor_west");d.appendChild(a);c.appendChild(d);var g=h("table","actionregion","top"),e=h("table","actionregion","right"),f,k=h("table","actionregion","left"),q=h("table","actionregion","bottom");if(2<Math.min(n.action_menu_columns,m)){f=h("table","actionregion","center");var l=h("td","actionpostd","hor_center"),c=h("td","actionpostd","hor_east");l.appendChild(f);
d.appendChild(l);d.appendChild(c)}else 1<Math.min(n.action_menu_columns,m)?(f=e,c=h("td","actionpostd","hor_east"),d.appendChild(c)):f=c=k;$([f,e]).hide();a.appendChild(g);c.appendChild(e);a.appendChild(k);a.appendChild(q);B(null,b,{top:g,left:k,center:f,right:e,bottom:q})},C=function(b,a){try{var d=function(){a&&w.ACTIONMENU.CLOSE_ALLOWED&&window.close()};a?sendMessage({method:"newTab",url:b},d):rea.tabs.getSelected(null,function(c){rea.tabs.sendMessage(c.id,{method:"loadUrl",url:b,newtab:a},d)})}catch(c){console.warn("lU:",
c)}},H=function(b){var a=confirm(b.msg),d={};a&&b.ok?d=b.ok:!a&&b.cancel&&(d=b.cancel);if(b.ok||b.cancel)a=!0;d.url&&sendMessage({method:"newTab",url:d.url},function(a){});return a},D=function(b,a,d){try{sendMessage({method:"reportAnIssue",uuid:b,to:a},function(a){d&&d()})}catch(c){console.warn("raI:",c)}},I=function(b,a){try{sendMessage({method:"buttonPress",name:b,data:a.data},function(b){a.reload&&rea.page.reload()})}catch(d){console.warn("rSU:",d)}},x={},L=function(b,a,d){document.body.addEventListener("keydown",
function(a){a.altKey||a.ctrlKey||a.shiftKey||Object.keys(x).forEach(function(b){(b=x[b])&&a.keyCode==b.key&&b.cb.apply(b.elem||window,[])})},!1)},G=function(b,a,d){b=b.charCodeAt(0);if(x[b])return console.log("MenuCmdKeyListener: ...failed!"),!1;x[b]={key:b,cb:a,elem:d};return!0},F=function(b,a){try{sendMessage({method:"execMenuCmd",id:b},function(b){a&&a()})}catch(d){console.warn("Error(eMC):",d)}},J=function(b,a,d){try{b={method:"modifyScriptOptions",uuid:b},a&&""!=a&&(b[a]=d),sendMessage(b,function(a){document.getElementById("action").innerHTML=
"";a&&(a.i18n&&k.setLocale(a.i18n),a.items&&(a.options&&(n=y.assign(n,a.options)),E(a.items)))})}catch(c){console.warn("Error(mSo): "+c.message)}};rea.extension.onMessage.addListener(function(b,a,d){"updateActions"==b.method?rea.page.reload():console.log("onMessage: Unknown method '"+b.method+"'")});(function(b,a,d){var c=Date.now();sendMessage({method:"loadTree",referrer:b,layout:!0,available_columns:m},function(b){b.options&&(n=y.assign(n,b.options));z.applyTheme(b.layout);b.i18n&&k.setLocale(b.i18n);
var e=Date.now()-c,f=function(){a(b)};!d||e>=d?f():window.setTimeout(f,d-e)})})("actions",function(b){if(b.options&&b.options.layout_user_css){var a=document.createElement("style");a.innerHTML=b.options.layout_user_css;(document.head||document.body||document.documentElement||document).appendChild(a)}L();E(b.items)},w.ACTIONMENU.MIN_DELAY)})});
