Registry.require(["crcrc","helper"],function(){var n=Registry.get("helper"),u=Registry.get("crcrc").cr,g=Registry.get("crcrc").crc,c={};Registry.register("layout/default/tabview","5665",{create:function(v,l,f,M){var a=n.filter(v,/[0-9a-zA-Z]/g);v=!1;void 0==f&&(f={tv:"tv",tv_table:"tv_table",tr_tabs:"tr_tabs",tr_content:"tr_content",td_content:"td_content",td_tabs:"td_tabs",tv_tabs_fill:"tv_tabs_fill",tv_tabs_table:"tv_tabs_table",tv_tabs_align:"tv_tabs_align",tv_contents:"tv_contents",
tv_tab_selected:"tv_tab tv_selected",tv_tab_close:"tv_tab_close",tv_tab:"tv_tab",tv_content:"tv_content"});var z=g("div",f.tv,"main"+a),m=g("table",f.tv_table+" noborder","main_table"+a);m.inserted?v=!0:(c[a]={},c[a].g_entries={},c[a].g_selectedId=null);var A=g("tr",f.tr_tabs,"tabs"+l.id+a),B=g("td",f.td_tabs,"pages"+a),C=g("div",f.tv_tabs_fill,"tv_tabs_fill"+a),D=g("div",f.tv_tabs_table,"tv_tabs_table"+a),q=g("div",f.tv_tabs_align,"tv_tabs_align"+a),E=g("tr",f.tr_content,"content"+l.id+a),F=g("td",
f.td_content,"content"+a),y=g("div",f.tv_contents,"tv_content"+a),G=u("tfoot","tv_footer_t"+a),H=u("tr","tv_footer_tr"+a),I=u("td","tv_footer_td"+a);G.appendChild(H);H.appendChild(I);D.appendChild(q);C.appendChild(D);B.appendChild(C);A.appendChild(B);m.appendChild(A);F.appendChild(y);E.appendChild(F);m.appendChild(E);m.appendChild(G);z.appendChild(m);l.appendChild(z);var J=function(a,c,b){c?a.setAttribute("style",b?n.staticVars.visible_move:n.staticVars.visible):a.setAttribute("style",b?n.staticVars.invisible_move:
n.staticVars.invisible);a.setAttribute("vis",c.toString())},K=function(d,e){var b=d.getId();c[a].g_entries[b]&&e!=c[a].g_entries[b].visible&&(c[a].g_entries[b].visible=e,J(c[a].g_entries[b].tab,e))},w=function(a,c){a&&J(a.content,c,!1)},N=function(d){for(var e=Object.keys(c[a].g_entries),b,h=0;b=e[h];h++)if(b=c[a].g_entries[b],b.tab.id==d.id)return b;return null},x=function(d){if(null===d)return null;for(var e=Object.keys(c[a].g_entries),b,h=0;b=e[h];h++)if(b=c[a].g_entries[b],b.entry.getId()==d)return b.entry;
return null},O=function(d){if(d.getId()!=c[a].g_selectedId){var e=d.getId();c[a].g_selectedId&&w(c[a].g_entries[c[a].g_selectedId],!1);Object.keys(c[a].g_entries).forEach(function(b){b=c[a].g_entries[b];b.entry.getId()==e?b.visible?b.selected||(b.tab.setAttribute("class",f.tv_tab_selected),w(b,!0),b.selected=!0):console.log("tv: WARN: tab selected but not visible!"):b.selected&&(b.tab.setAttribute("class",f.tv_tab),w(b,!1),b.selected=!1)});c[a].g_selectedId=e}},L=function(d){d.hide();d=d.getId();
if(d=c[a].g_entries[d]){d.tab.parentNode.removeChild(d.tab);d.content.parentNode.removeChild(d.content);a:{d=d.tab;for(var e=Object.keys(c[a].g_entries),b,h=0;b=e[h];h++)if(c[a].g_entries[b].tab.id==d.id){d=b;break a}d=null}d&&delete c[a].g_entries[d]}else console.log("tv: WARN: tab not part of tabview!")};l=null;v?l=c[a].tv:(l={getTabById:x,getSelectedTab:function(){return x(c[a].g_selectedId)},getNextTab:function(d){var e=$(q).find("div[tvid]"),b;c[a].g_selectedId&&e.each(function(d,f){b||$(f).attr("tvid")===
c[a].g_selectedId&&(b=$(e.get(d+1)).attr("tvid"))});return x(b||e.first().attr("tvid"))},getPreviousTab:function(d){var e=$(q).find("div[tvid]"),b;c[a].g_selectedId&&e.each(function(d,f){b||$(f).attr("tvid")===c[a].g_selectedId&&(b=$(e.get(d-1)).attr("tvid"))});return x(b||e.last().attr("tvid"))},removeTab:L,appendTab:function(a,c,b,f,g){return this.insertTab(void 0,a,c,b,f,g)},insertTab:function(d,e,b,h,l,r){null===d&&(d=q.firstChild);var p="tab_"+e,k=u("div",p,"content"+a),t=void 0!==k.inserted&&
1==k.inserted,n=u("div",p,"head_text"+a);b.appendChild(n);r&&(p=g("div",f.tv_tab_close,p,"tv_close"+a,"tab_close"),p.inserted||p.addEventListener("click",function(){r()}),b.appendChild(p));if(t){if(t=N(k))return t.entry;console.log("tv: WARN: old tab, but not in tabs collection!")}var m,t=function(a){""!=a.target.className&&a.target.className==f.tv_tab_close||m.select()};k.setAttribute("tvid",e);k.addEventListener("click",t);b.addEventListener("click",t);k.setAttribute("name","tabview_tab"+a);k.setAttribute("class",
f.tv_tab);k.appendChild(b);d?q.insertBefore(k,d):q.appendChild(k);h.setAttribute("name","tabview_content"+a);h.setAttribute("class",f.tv_content);y.appendChild(h);m={getId:function(){return e},isVisible:function(){return"true"==k.getAttribute("vis")},isSelected:function(){return c[a].g_selectedId==this.getId()},isCloseable:function(){return!!r},remove:function(){L(this)},hide:function(){var b=this.getId(),d=b==c[a].g_selectedId;c[a].g_entries[b]?K(this,!1):console.log("tv: WARN: tab not part of tabview!");
if(d){var d=b=null,e;for(e in c[a].g_entries)c[a].g_entries[e].visible&&(b=c[a].g_entries[e],d||b.closable||(d=b));M||b.closable||(b=d);b?b.entry.select():(c[a].g_selectedId=null,console.log("tv: WARN: selected tab set, but entry collection empty!"))}},show:function(){var b=this.getId();c[a].g_entries[b]?K(this,!0):console.log("tv: WARN: tab not part of tabview!")},select:function(){O(this);l&&l()},setHeading:function(a,c,d){var e=b.firstChild;if(c&&a.length>c){var f=Math.round(c/2);e.textContent=
a.substr(0,f)+"..."+a.substr(f-c);e.title=d||a}else e.textContent=a},toggleClass:function(a,c){$(b,y).toggleClass(a,c)},close:function(){r&&r()}};c[a].g_entries[e]={entry:m,tab:k,content:h,closable:null!=r};w(c[a].g_entries[e],!1);m.show();return m},setFooter:function(a){I.appendChild(a)}},c[a].tv=l);return l}})});
